cookie:
  expiry_days: 30
  key: xyzabc
  name: data_dashboard
credentials:
  usernames:
    dbaldwin:
      email: dbaldwin@gmail.com
      name: David Baldwin
      password: '$2b$12$wTBW5/7yzE1/l5bmUXyCF.tYbQNO8JX/uDqc1l0fYLuYNVB8IwOfW'
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$pCLOJQYiXq3T/iF2Nclnh.UwwifsH/oaLs4VARF9P1k1DFUUP9Xym'
preauthorized:
  emails:
  - melsby@gmail.com
