cookie:
  expiry_days: 30
  key: xyzabc
  name: data_dashboard
credentials:
  usernames:
    dbaldwin:
      email: dbaldwin@gmail.com
      name: David Baldwin
      password: abcdef
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: hellomawa
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: sarsarle
    rcouper:
      email: rcouper@gmail.com
      name: Ross Couper
      password: atlutaddimanthoni
preauthorized:
  emails:
  - melsby@gmail.com
